#n1=input('Digite um valor:')
#n2=input('Digite outro:')
#s=int(n1)+int(n2)
#print('A soma entre {} e {} vale {}'.format(n1,n2,s))

a=input('Digite algo: ')
print(f'Só tem espaços? {a.isspace()}')
print(f'É numérico? {a.isnumeric()}')
print(f'É alfabético? {a.isalpha()}')
print(f'É alfanumérico? {a.isalnum()}')
print(f'Está em letras maiúsculas?{a.isupper()}')
print(f'Está em letras minúsculas? {a.islower()}')
print(f'Está capitalizada? {a.istitle()}')
